# https://taskfile.dev

version: "3"

tasks:
  run:
    desc: Run the backend
    cmds:
      - cargo run -p server

  dc-dev:
    aliases:
      - dc
    desc: Run on the docker-compose dev stack
    cmds:
      - docker-compose -f docker-compose.yml -f dev.docker-compose.yml {{.CLI_ARGS}}
