# https://taskfile.dev

version: "3"

tasks:
  run-server:
    aliases:
      - run
    desc: Run the backend
    cmds:
      - cargo run -p server

  run-webapp:
    aliases:
      - run-web
      - web
    desc: Run the web app
    deps:
      - deps-webapp
    dir: webapp
    cmds:
      - bun run dev

  deps-webapp:
    dir: webapp
    sources:
      - ./package.json
      - ./bun.lockb
    cmds:
      - bun install

  dc-dev:
    aliases:
      - dc
    desc: Run on the docker-compose dev stack
    cmds:
      - docker-compose -f docker-compose.yml -f dev.docker-compose.yml {{.CLI_ARGS}}
