[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.21"
openid = "0.14.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.203"
url = "2.5.2"
